services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cqupt-ics-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  cqupt-ics-server:
    image: cqupt-ics-server:latest
    ports:
      - "9921:3000"
    environment:
      - PORT=3000
      - RUST_LOG=warn
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cqupt-ics-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      replicas: 1

volumes:
  redis_data:

networks:
  cqupt-ics-network:
    driver: bridge
